ALTER TABLE assets ADD COLUMN IF NOT EXISTS section_179_election BOOLEAN DEFAULT FALSE;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS bonus_depreciation_election BOOLEAN DEFAULT FALSE;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS section_179_amount NUMERIC DEFAULT 0;